---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/hyurii/argocd_gitops.git
    targetRevision: HEAD
    path: environments/staging/app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
